@baseURL = http://localhost:3000

GET {{baseURL}}/api?name=test
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

> {{statusCode()}} 200
> {{jsonpath "$.name"}} test

POST {{baseURL}}/api
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "name": "test"
}

> {{statusCode()}} 200
> {{jsonpath "$.name"}} test

GET {{baseURL}}/api?name=test
Authorization: Basic YWRtaW46wrongpassword

> {{statusCode()}} 401
